from generate_spells import char_sheet_format_spells, get_spellcaster_details
from generate_equipment import fill_coin_slots
from generate_proficiency import *
import PyPDF2

# for filling one-pager character sheet
def char_dict_to_pdf(char_dict):
    emptysheet = PyPDF2.PdfFileReader('./charactersheets/charsheet.pdf')
    writer = PyPDF2.PdfFileWriter()
    writer.insertPage(emptysheet.getPage(0))
    proficiency_bonus = calc_proficiency_bonus(char_dict['level'])
    coin_dict = fill_coin_slots(char_dict['equipment'])
    to_be_filled = {
    'ClassLevel': char_dict['class'] + ' ' + str(char_dict['level']),
    'Background': char_dict['background']['Title'],
    'PlayerName': '',
    'CharacterName': char_dict['name'],
    'Race ': char_dict['race'],
    'Alignment': '',
    'XP': '',
    'Inspiration': 'x',
    'STR': str(char_dict['stats']['Total Stats']['STR']),
    'ProfBonus': '+' + str(proficiency_bonus),
    'AC': str(char_dict['armorclass']),
    'Initiative': str(10+char_dict['stats']['Modifiers']['DEX']),
    'Speed': '30',
    'PersonalityTraits ': char_dict['background']['Trait'],
    'STRmod': str(char_dict['stats']['Modifiers']['STR']),
    'HPMax': str(char_dict['hitpoints']),
    'ST Strength': '+' + str(char_dict['stats']['Modifiers']['STR']),
    'DEX': str(char_dict['stats']['Total Stats']['DEX']),
    'HPCurrent': str(char_dict['hitpoints']),
    'Ideals': char_dict['background']['Ideal'],
    'DEXmod ': str(char_dict['stats']['Modifiers']['DEX']),
    'HPTemp': '',
    'Bonds': char_dict['background']['Bond'],
    'CON': str(char_dict['stats']['Total Stats']['CON']),
    'HDTotal': str(char_dict['level']),
    'CONmod': str(char_dict['stats']['Modifiers']['CON']),
    'HD': str(char_dict['level']),
    'Flaws': char_dict['background']['Flaw'],
    'INT': str(char_dict['stats']['Total Stats']['INT']),
    'ST Dexterity': '+' + str(char_dict['proficiency']['Saving Throws']['DEX']),
    'ST Constitution': '+' + str(char_dict['proficiency']['Saving Throws']['CON']),
    'ST Intelligence': '+' + str(char_dict['proficiency']['Saving Throws']['INT']),
    'ST Wisdom': '+' + str(char_dict['proficiency']['Saving Throws']['WIS']),
    'ST Charisma': '+' + str(char_dict['proficiency']['Saving Throws']['CHA']),
    'Acrobatics': '+' + str(char_dict['proficiency']['Skills']['Acrobatics']),
    'Animal': '+' + str(char_dict['proficiency']['Skills']['Animal']),
    'Athletics': '+' + str(char_dict['proficiency']['Skills']['Athletics']),
    'Deception ': '+' + str(char_dict['proficiency']['Skills']['Deception']),
    'History ': '+' + str(char_dict['proficiency']['Skills']['History']),
    'Insight': '+' + str(char_dict['proficiency']['Skills']['Insight']),
    'Intimidation': '+' + str(char_dict['proficiency']['Skills']['Intimidation']),
    'Wpn Name': char_dict['weapons']['Weapon 1']['Name'],
    'Wpn1 AtkBonus': char_dict['weapons']['Weapon 1']['AtkBonus'],
    'Wpn1 Damage': char_dict['weapons']['Weapon 1']['Damage'],
    'INTmod': str(char_dict['stats']['Modifiers']['INT']),
    'Wpn Name 2': char_dict['weapons']['Weapon 2']['Name'],
    'Wpn2 AtkBonus ': char_dict['weapons']['Weapon 2']['AtkBonus'],
    'Wpn2 Damage ': char_dict['weapons']['Weapon 2']['Damage'],
    'Investigation ': '+' + str(char_dict['proficiency']['Skills']['Investigation']),
    'WIS': str(char_dict['stats']['Total Stats']['INT']),
    'Wpn Name 3': char_dict['weapons']['Weapon 3']['Name'],
    'Wpn3 AtkBonus  ': char_dict['weapons']['Weapon 3']['AtkBonus'],
    'Arcana': '+' + str(char_dict['proficiency']['Skills']['Arcana']),
    'Wpn3 Damage ': char_dict['weapons']['Weapon 3']['Damage'],
    'Perception ': '+' + str(char_dict['proficiency']['Skills']['Perception']),
    'WISmod': str(char_dict['stats']['Modifiers']['INT']),
    'CHA': str(char_dict['stats']['Total Stats']['CHA']),
    'Nature': '+' + str(char_dict['proficiency']['Skills']['Nature']),
    'Performance': '+' + str(char_dict['proficiency']['Skills']['Performance']),
    'Medicine': '+' + str(char_dict['proficiency']['Skills']['Medicine']),
    'Religion': '+' + str(char_dict['proficiency']['Skills']['Religion']),
    'Stealth ': '+' + str(char_dict['proficiency']['Skills']['Stealth']),
    'Persuasion': '+' + str(char_dict['proficiency']['Skills']['Persuasion']),
    'SleightofHand': '+' + str(char_dict['proficiency']['Skills']['SleightofHand']),
    'CHamod': str(char_dict['stats']['Modifiers']['CHA']),
    'Survival': '+' + str(char_dict['proficiency']['Skills']['Survival']),
    'AttacksSpellcasting': char_dict['spells'],
    'Passive': str(10+char_dict['proficiency']['Skills']['Perception']),
    'CP': coin_dict['copper'],
    'ProficienciesLang': str(char_dict['proficiency']['Armor']) + ' ' + str(char_dict['proficiency']['Weapons']) + ' ' + str(char_dict['proficiency']['Tools']) + ' ' + str(char_dict['proficiency']['Proficient Skills']),
    'SP': coin_dict['silver'],
    'EP': coin_dict['electrum'],
    'GP': coin_dict['gold'],
    'PP': coin_dict['platinum'],
    'Equipment': char_dict['equipment'],
    'Features and Traits': char_dict['features']
    }
    writer.updatePageFormFieldValues(writer.getPage(0), to_be_filled)
    filename = char_dict['name']
    filledsheet = open('./charactersheets/'+filename+'.pdf', 'wb')
    writer.write(filledsheet)
    return 'Character Sheet Created'

# for filling three-pager character sheet
def char_dict_to_pdf_ext(char_dict):
    emptysheet = PyPDF2.PdfFileReader('./charactersheets/charsheet_ext.pdf')
    writer = PyPDF2.PdfFileWriter()
    writer.insertPage(emptysheet.getPage(2))
    writer.insertPage(emptysheet.getPage(1))
    writer.insertPage(emptysheet.getPage(0))
    proficiency_bonus = calc_proficiency_bonus(char_dict['level'])
    spell_slots_dict, spells_dict = char_sheet_format_spells(char_dict)
    spellcasting_class, spellcasting_ability, spell_save_dc, spell_atk_bonus = get_spellcaster_details(char_dict)
    coin_dict = fill_coin_slots(char_dict['equipment'])
    to_be_filled = {
    'CharacterName 2': char_dict['name'],
    'Age': '',
    'Height': '',
    'Weight': '',
    'Eyes': '',
    'Skin': '',
    'Hair': '',
    'Allies': '',
    'FactionName': '',
    'Backstory': '',
    'Feat+Traits': char_dict['features'],
    'Treasure': '',
    'ClassLevel': char_dict['class'] + ' ' + str(char_dict['level']),
    'Background': char_dict['background']['Title'],
    'PlayerName': '',
    'CharacterName': char_dict['name'],
    'Race ': char_dict['race'],
    'Alignment': '',
    'XP': '',
    'Inspiration': 'x',
    'STR': str(char_dict['stats']['Total Stats']['STR']),
    'ProfBonus': '+' + str(proficiency_bonus),
    'AC': str(char_dict['armorclass']),
    'Initiative': str(10+char_dict['stats']['Modifiers']['DEX']),
    'Speed': '30',
    'PersonalityTraits ': char_dict['background']['Trait'],
    'STRmod': str(char_dict['stats']['Modifiers']['STR']),
    'HPMax': str(char_dict['hitpoints']),
    'ST Strength': str(char_dict['proficiency']['Saving Throws']['STR']),
    'DEX': str(char_dict['stats']['Total Stats']['DEX']),
    'HPCurrent': str(char_dict['hitpoints']),
    'Ideals': char_dict['background']['Ideal'],
    'DEXmod ': str(char_dict['stats']['Modifiers']['DEX']),
    'HPTemp': '',
    'Bonds': char_dict['background']['Bond'],
    'CON': str(char_dict['stats']['Total Stats']['CON']),
    'HDTotal': str(char_dict['level']),
    'CONmod': str(char_dict['stats']['Modifiers']['CON']),
    'HD': str(char_dict['level']),
    'Flaws': char_dict['background']['Flaw'],
    'INT': str(char_dict['stats']['Total Stats']['INT']),
    'ST Dexterity': str(char_dict['proficiency']['Saving Throws']['DEX']),
    'ST Constitution': str(char_dict['proficiency']['Saving Throws']['CON']),
    'ST Intelligence': str(char_dict['proficiency']['Saving Throws']['INT']),
    'ST Wisdom': str(char_dict['proficiency']['Saving Throws']['WIS']),
    'ST Charisma': str(char_dict['proficiency']['Saving Throws']['CHA']),
    'Acrobatics': '+' + str(char_dict['proficiency']['Skills']['Acrobatics']),
    'Animal': '+' + str(char_dict['proficiency']['Skills']['Animal']),
    'Athletics': '+' + str(char_dict['proficiency']['Skills']['Athletics']),
    'Deception ': '+' + str(char_dict['proficiency']['Skills']['Deception']),
    'History ': '+' + str(char_dict['proficiency']['Skills']['History']),
    'Insight': '+' + str(char_dict['proficiency']['Skills']['Insight']),
    'Intimidation': '+' + str(char_dict['proficiency']['Skills']['Intimidation']),
    'Wpn Name': char_dict['weapons']['Weapon 1']['Name'],
    'Wpn1 AtkBonus': char_dict['weapons']['Weapon 1']['AtkBonus'],
    'Wpn1 Damage': char_dict['weapons']['Weapon 1']['Damage'],
    'INTmod': str(char_dict['stats']['Modifiers']['INT']),
    'Wpn Name 2': char_dict['weapons']['Weapon 2']['Name'],
    'Wpn2 AtkBonus ': char_dict['weapons']['Weapon 2']['AtkBonus'],
    'Wpn2 Damage ': char_dict['weapons']['Weapon 2']['Damage'],
    'Investigation ': '+' + str(char_dict['proficiency']['Skills']['Investigation']),
    'WIS': str(char_dict['stats']['Total Stats']['WIS']),
    'Wpn Name 3': char_dict['weapons']['Weapon 3']['Name'],
    'Wpn3 AtkBonus  ': char_dict['weapons']['Weapon 3']['AtkBonus'],
    'Arcana': '+' + str(char_dict['proficiency']['Skills']['Arcana']),
    'Wpn3 Damage ': char_dict['weapons']['Weapon 3']['Damage'],
    'Perception ': '+' + str(char_dict['proficiency']['Skills']['Perception']),
    'WISmod': str(char_dict['stats']['Modifiers']['WIS']),
    'CHA': str(char_dict['stats']['Total Stats']['CHA']),
    'Nature': '+' + str(char_dict['proficiency']['Skills']['Nature']),
    'Performance': '+' + str(char_dict['proficiency']['Skills']['Performance']),
    'Medicine': '+' + str(char_dict['proficiency']['Skills']['Medicine']),
    'Religion': '+' + str(char_dict['proficiency']['Skills']['Religion']),
    'Stealth ': '+' + str(char_dict['proficiency']['Skills']['Stealth']),
    'Persuasion': '+' + str(char_dict['proficiency']['Skills']['Persuasion']),
    'SleightofHand': '+' + str(char_dict['proficiency']['Skills']['SleightofHand']),
    'CHamod': str(char_dict['stats']['Modifiers']['CHA']),
    'Survival': '+' + str(char_dict['proficiency']['Skills']['Survival']),
    'AttacksSpellcasting': '',
    'Passive': str(10+char_dict['proficiency']['Skills']['Perception']),
    'CP': coin_dict['copper'],
    'ProficienciesLang': str(char_dict['proficiency']['Armor']) + ' ' + str(char_dict['proficiency']['Weapons']) + ' ' + str(char_dict['proficiency']['Tools']) + ' ' + str(char_dict['proficiency']['Proficient Skills']),
    'SP': coin_dict['silver'],
    'EP': coin_dict['electrum'],
    'GP': coin_dict['gold'],
    'PP': coin_dict['platinum'],
    'Equipment': char_dict['equipment'],
    'Features and Traits': char_dict['features'],
    'Spellcasting Class 2': spellcasting_class,
    'SpellcastingAbility 2': spellcasting_ability,
    'SpellSaveDC  2': 'DC '+ str(spell_save_dc),
    'SpellAtkBonus 2': '+' + str(spell_atk_bonus),
    'SlotsTotal 19': str(spell_slots_dict['1st Level']),
    'SlotsRemaining 19': str(spell_slots_dict['1st Level']),
    'Spells 1014': spells_dict['Cantrip'][0],
    'Spells 1016': spells_dict['Cantrip'][1],
    'Spells 1017': spells_dict['Cantrip'][2],
    'Spells 1018': spells_dict['Cantrip'][3],
    'Spells 1019': spells_dict['Cantrip'][4],
    'Spells 1020': spells_dict['Cantrip'][5],
    'Spells 1021': spells_dict['Cantrip'][6],
    'Spells 1022': spells_dict['Cantrip'][7],
    'Spells 1015': spells_dict['1st Level'][0],
    'Spells 1023': spells_dict['1st Level'][1],
    'Spells 1024': spells_dict['1st Level'][2],
    'Spells 1025': spells_dict['1st Level'][3],
    'Spells 1026': spells_dict['1st Level'][4],
    'Spells 1027': spells_dict['1st Level'][5],
    'Spells 1028': spells_dict['1st Level'][6],
    'Spells 1029': spells_dict['1st Level'][7],
    'Spells 1030': spells_dict['1st Level'][8],
    'Spells 1031': spells_dict['1st Level'][9],
    'Spells 1032': spells_dict['1st Level'][10],
    'Spells 1033': spells_dict['1st Level'][11],
    'SlotsTotal 20': str(spell_slots_dict['2nd Level']),
    'SlotsRemaining 20': str(spell_slots_dict['2nd Level']),
    'Spells 1046': spells_dict['2nd Level'][0],
    'Spells 1034': spells_dict['2nd Level'][1],
    'Spells 1035': spells_dict['2nd Level'][2],
    'Spells 1036': spells_dict['2nd Level'][3],
    'Spells 1037': spells_dict['2nd Level'][4],
    'Spells 1038': spells_dict['2nd Level'][5],
    'Spells 1039': spells_dict['2nd Level'][6],
    'Spells 1040': spells_dict['2nd Level'][7],
    'Spells 1041': spells_dict['2nd Level'][8],
    'Spells 1042': spells_dict['2nd Level'][9],
    'Spells 1043': spells_dict['2nd Level'][10],
    'Spells 1044': spells_dict['2nd Level'][11],
    'Spells 1045': spells_dict['2nd Level'][12],
    'SlotsTotal 21': str(spell_slots_dict['3rd Level']),
    'SlotsRemaining 21': str(spell_slots_dict['3rd Level']),
    'Spells 1048': spells_dict['3rd Level'][0],
    'Spells 1047': spells_dict['3rd Level'][1],
    'Spells 1049': spells_dict['3rd Level'][2],
    'Spells 1050': spells_dict['3rd Level'][3],
    'Spells 1051': spells_dict['3rd Level'][4],
    'Spells 1052': spells_dict['3rd Level'][5],
    'Spells 1053': spells_dict['3rd Level'][6],
    'Spells 1054': spells_dict['3rd Level'][7],
    'Spells 1055': spells_dict['3rd Level'][8],
    'Spells 1056': spells_dict['3rd Level'][9],
    'Spells 1057': spells_dict['3rd Level'][10],
    'Spells 1058': spells_dict['3rd Level'][11],
    'Spells 1059': spells_dict['3rd Level'][12],
    'SlotsTotal 22': str(spell_slots_dict['4th Level']),
    'SlotsRemaining 22': str(spell_slots_dict['4th Level']),
    'Spells 1061': spells_dict['4th Level'][0],
    'Spells 1060': spells_dict['4th Level'][1],
    'Spells 1062': spells_dict['4th Level'][2],
    'Spells 1063': spells_dict['4th Level'][3],
    'Spells 1064': spells_dict['4th Level'][4],
    'Spells 1065': spells_dict['4th Level'][5],
    'Spells 1066': spells_dict['4th Level'][6],
    'Spells 1067': spells_dict['4th Level'][7],
    'Spells 1068': spells_dict['4th Level'][8],
    'Spells 1069': spells_dict['4th Level'][9],
    'Spells 1070': spells_dict['4th Level'][10],
    'Spells 1071': spells_dict['4th Level'][11],
    'Spells 1072': spells_dict['4th Level'][12],
    'SlotsTotal 23': str(spell_slots_dict['5th Level']),
    'SlotsRemaining 23': str(spell_slots_dict['5th Level']),
    'Spells 1074': spells_dict['5th Level'][0],
    'Spells 1073': spells_dict['5th Level'][1],
    'Spells 1075': spells_dict['5th Level'][2],
    'Spells 1076': spells_dict['5th Level'][3],
    'Spells 1077': spells_dict['5th Level'][4],
    'Spells 1078': spells_dict['5th Level'][5],
    'Spells 1079': spells_dict['5th Level'][6],
    'Spells 1080': spells_dict['5th Level'][7],
    'Spells 1081': spells_dict['5th Level'][8],
    'SlotsTotal 24': str(spell_slots_dict['6th Level']),
    'SlotsRemaining 24': str(spell_slots_dict['6th Level']),
    'Spells 1083': spells_dict['6th Level'][0],
    'Spells 1082': spells_dict['6th Level'][1],
    'Spells 1084': spells_dict['6th Level'][2],
    'Spells 1085': spells_dict['6th Level'][3],
    'Spells 1086': spells_dict['6th Level'][4],
    'Spells 1087': spells_dict['6th Level'][5],
    'Spells 1088': spells_dict['6th Level'][6],
    'Spells 1089': spells_dict['6th Level'][7],
    'Spells 1090': spells_dict['6th Level'][8],
    'SlotsTotal 25': str(spell_slots_dict['7th Level']),
    'SlotsRemaining 25': str(spell_slots_dict['7th Level']),
    'Spells 1092': spells_dict['7th Level'][0],
    'Spells 1091': spells_dict['7th Level'][1],
    'Spells 1093': spells_dict['7th Level'][2],
    'Spells 1094': spells_dict['7th Level'][3],
    'Spells 1095': spells_dict['7th Level'][4],
    'Spells 1096': spells_dict['7th Level'][5],
    'Spells 1097': spells_dict['7th Level'][6],
    'Spells 1098': spells_dict['7th Level'][7],
    'Spells 1099': spells_dict['7th Level'][8],
    'SlotsTotal 26': str(spell_slots_dict['8th Level']),
    'SlotsRemaining 26': str(spell_slots_dict['8th Level']),
    'Spells 10101': spells_dict['8th Level'][0],
    'Spells 10100': spells_dict['8th Level'][1],
    'Spells 10102': spells_dict['8th Level'][2],
    'Spells 10103': spells_dict['8th Level'][3],
    'Spells 10104': spells_dict['8th Level'][4],
    'Spells 10105': spells_dict['8th Level'][5],
    'Spells 10106': spells_dict['8th Level'][6],
    'SlotsTotal 27': str(spell_slots_dict['9th Level']),
    'SlotsRemaining 27': str(spell_slots_dict['9th Level']),
    'Spells 10108': spells_dict['9th Level'][0],
    'Spells 10107': spells_dict['9th Level'][1],
    'Spells 10109': spells_dict['9th Level'][2],
    'Spells 101010': spells_dict['9th Level'][3],
    'Spells 101011': spells_dict['9th Level'][4],
    'Spells 101012': spells_dict['9th Level'][5],
    'Spells 101013': spells_dict['9th Level'][6]
    }
    writer.updatePageFormFieldValues(writer.getPage(0), to_be_filled)
    writer.updatePageFormFieldValues(writer.getPage(1), to_be_filled)
    writer.updatePageFormFieldValues(writer.getPage(2), to_be_filled)
    filename = char_dict['name']
    filledsheet = open('./charactersheets/'+filename+'.pdf', 'wb')
    writer.write(filledsheet)
    return 'Character Sheet Created'
